import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Playfair_Display,  EB_Garamond, Outfit, Open_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/Footer";
import ReduxProvider from "@/components/reduxProvider";
// import { EB_Garamond } from "next/font/google";



const ebGaramond = EB_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you'll actually use
  variable: "--font-eb-garamond",
});
const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you'll actually use
  variable: "--font-outfit",
});
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you'll actually use
  variable: "--font-openSans",
});
const playfairDisplayHeading = Playfair_Display({ subsets: ['latin'], variable: '--font-heading' });
const notoSans = Noto_Sans({ subsets: ['latin'], variable: '--font-sans' });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", notoSans.variable, playfairDisplayHeading.variable, ebGaramond.variable, outfit.variable, openSans.variable)}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">
        <ReduxProvider>
          <Navbar />
        {children}
        <Footer/>
        </ReduxProvider>
        
      </body>
    </html>
  );
}